name: RandomPotionEffects
version: '${project.version}'
main: me.redstonenotplaced.randompotioneffects.RandomPotionEffects
api-version: 1.18
authors: [ RedstoneNotPlaced ]
description: Minecraft but every 30 seconds it gives you a random potion effect

commands:
  start:
    description: Starts the challenge
    permission: rpe.command.start
  end:
    description: Ends the challenge
    permission: rpe.command.end

permissions:
  rpe.command.start:
    description: Permission for the start command
  rpe.command.end:
    description: Permission for the end command